#!/bin/sh
# Writes skills/forge/references/commands.md from the help text of every command.
set -eu

root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
FORGE_HOME=$root
for lib in util json detect args help dispatch; do
    . "$root/lib/core/$lib.sh"
done
for file in "$root"/lib/cmd/*.sh; do
    . "$file"
done

out="$root/skills/forge/references/commands.md"
{
    echo '# forge command reference'
    echo
    echo 'Generated by `just docs` from `forge <command> --help`. Do not edit by hand.'
    echo 'Every command also takes the global flags `-R/--repo`, `--json`, `--jq <expr>`, `-h/--help`.'
    echo 'Exit codes everywhere: 0 success, 1 failure, 2 wrong usage, 3 not supported on this platform, 4 not found.'
    echo
    echo '## Contents'
    echo
    sh "$root/scripts/forge-commands.sh" | while IFS=' ' read -r node path; do
        printf -- '- [forge %s](#forge-%s)\n' "$path" "$(printf '%s' "$path" | tr ' ' -)"
    done
    sh "$root/scripts/forge-commands.sh" | while IFS=' ' read -r node path; do
        echo
        echo "## forge $path"
        echo
        echo '```text'
        "help_$node"
        echo '```'
    done
} >"$out"
printf 'wrote %s\n' "${out#"$root"/}"
