#!/bin/sh
# Moves the release on from where it stands; safe to run again at any point.
#
# Usage:
#   sh scripts/release.sh [VERSION=<tag>]
#
#   The version on HEAD was set by a release commit,     tag that commit and publish the
#   and has no tag or no platform release yet             release from its CHANGELOG section
#   Otherwise                                            prepare the next release: branch
#                                                        release/<tag> with the changelog and
#                                                        the VERSION file, pushed, request
#                                                        opened or updated
#
#   VERSION is the tag to prepare, shaped as release.tag_template in workflow.toml. Worked out
#   from the commits since the last tag by default; that needs a semantic version.

set -eu

ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)

config() {
    sh "$ROOT/scripts/workflow.sh" get "$@"
}

forge() {
    sh "$ROOT/bin/forge" "$@"
}

RELEASE_BRANCH=$(config git.default_branch)
VERSION_PATTERN=$(config release.version_pattern)
TAG_TEMPLATE=$(config release.tag_template)

VERSION=
TEMP_FILE=
RETURN_TO=

usage() {
    sed -n '/^# Usage:/,/^$/{ s/^# \{0,1\}//; p; }' "$0"
}

for arg in "$@"; do
    case $arg in
        VERSION=*) VERSION=${arg#VERSION=} ;;
        -h | --help | help) usage; exit 0 ;;
        *) usage >&2; exit 2 ;;
    esac
done

step() {
    printf '\n\033[0;36m==>\033[0m %s\n' "$1"
}

fail() {
    printf '\033[0;31m!!\033[0m %s\n' "$1" >&2
    exit 1
}

cleanup() {
    [ -z "$TEMP_FILE" ] || rm -f "$TEMP_FILE"
    [ -z "$RETURN_TO" ] || git checkout --quiet --force "$RETURN_TO"
}
trap cleanup EXIT

if command jq -b -n null >/dev/null 2>&1; then
    jqx() { command jq -b "$@"; }
else
    jqx() { command jq "$@"; }
fi

TAG_PREFIX=${TAG_TEMPLATE%%"{version}"*}
TAG_SUFFIX=${TAG_TEMPLATE#*"{version}"}

tag_of() {
    printf '%s%s%s' "$TAG_PREFIX" "$1" "$TAG_SUFFIX"
}

# The version inside a tag, or failure when the tag does not fit the template.
version_of() {
    version_of_v=${1#"$TAG_PREFIX"}
    version_of_v=${version_of_v%"$TAG_SUFFIX"}
    [ "$(tag_of "$version_of_v")" = "$1" ] || return 1
    printf '%s' "$version_of_v" | grep -Eqx "$VERSION_PATTERN" || return 1
    printf '%s' "$version_of_v"
}

version_at() {
    git show "$1:VERSION" 2>/dev/null | tr -d '\r\n'
}

regex_literal() {
    printf '%s' "$1" | sed 's/[][\.^$*+?(){}|/]/\\&/g'
}

remote_tag_exists() {
    git ls-remote --exit-code --tags origin "refs/tags/$1" >/dev/null 2>&1
}

is_release_commit() {
    case $(git log -1 --format=%s "$1") in
        "chore(release): $2" | "chore(release): $2 ("*) return 0 ;;
    esac
    return 1
}

release_exists() {
    release_exists_status=0
    forge release view "$1" >/dev/null 2>&1 || release_exists_status=$?
    case $release_exists_status in
        0) return 0 ;;
        4) return 1 ;;
        *) fail "Cannot tell whether release $1 exists (forge release view exited $release_exists_status)" ;;
    esac
}

changelog_section() {
    awk -v heading="## [$1]" '
        index($0, heading) == 1 { found = 1; next }
        found && /^## \[/ { exit }
        found { lines[++count] = $0 }
        END {
            first = 1
            while (first <= count && lines[first] ~ /^[[:space:]]*$/) first++
            last = count
            while (last >= first && lines[last] ~ /^[[:space:]]*$/) last--
            for (i = first; i <= last; i++) print lines[i]
        }
    '
}

short() {
    printf '%s' "$1" | cut -c1-12
}

publish() {
    publish_version=$1
    publish_tag=$(tag_of "$publish_version")
    publish_commit=$2

    TEMP_FILE=$(mktemp)
    git show "$publish_commit:CHANGELOG.md" | changelog_section "$publish_version" >"$TEMP_FILE"
    [ -s "$TEMP_FILE" ] || fail "CHANGELOG.md at $(short "$publish_commit") has no section for $publish_version"

    if ! remote_tag_exists "$publish_tag"; then
        step "Tag $publish_tag on $(short "$publish_commit")"
        if git rev-parse --verify --quiet "refs/tags/$publish_tag" >/dev/null; then
            [ "$(git rev-parse "$publish_tag^{commit}")" = "$publish_commit" ] ||
                fail "Local tag $publish_tag points elsewhere than $(short "$publish_commit")"
        else
            git tag -a "$publish_tag" "$publish_commit" -m "$publish_tag"
        fi
        git push origin "refs/tags/$publish_tag"
    fi

    step "Release $publish_tag"
    forge release publish "$publish_tag" --title "$publish_tag" --body-file "$TEMP_FILE"

    step "Done"
    echo "  Released: $publish_tag"
}

request_description() {
    cat <<EOF
## Context

No ticket — release $1, prepared by \`just release\`.

## Changes

The $1 section of CHANGELOG.md, and the version in VERSION. The section is in the diff; it is
not copied here, so a rerun of \`just release\` cannot leave this text stale.

## How it was checked

Changelog generated by git-cliff from the commits since $2; nothing edited by hand.

## Review focus

Every change since $2 is listed, and the version fits what it holds.
EOF
}

prepare() {
    prepare_current=$1

    [ "$(git rev-parse HEAD)" = "$(git rev-parse "origin/$RELEASE_BRANCH")" ] ||
        fail "A release is prepared from the tip of origin/$RELEASE_BRANCH: pull or check it out first"
    command -v git-cliff >/dev/null 2>&1 || fail "git-cliff is required: https://git-cliff.org/docs/installation"

    if [ -z "$VERSION" ]; then
        VERSION=$(git-cliff --bumped-version 2>/dev/null) || fail "Could not work out the next version"
        if [ "$VERSION" = "$(tag_of "$prepare_current")" ]; then
            echo "Nothing to release since $VERSION"
            return
        fi
    fi
    prepare_version=$(version_of "$VERSION") ||
        fail "$VERSION does not match $TAG_TEMPLATE with version $VERSION_PATTERN"
    prepare_tag=$(tag_of "$prepare_version")
    [ "$prepare_version" != "$prepare_current" ] &&
        [ "$(printf '%s\n%s\n' "$prepare_current" "$prepare_version" | sort -t. -k1,1n -k2,2n -k3,3n | tail -n 1)" = "$prepare_version" ] ||
        fail "Version $prepare_version is not above the current $prepare_current"
    prepare_branch="release/$prepare_tag"
    ! remote_tag_exists "$prepare_tag" || fail "Tag $prepare_tag already exists"

    prepare_open=$(forge request list --limit 100 --json |
        jqx -r --arg branch "$prepare_branch" \
            '.[] | select((.source_branch | startswith("release/")) and .source_branch != $branch) | .url')
    [ -z "$prepare_open" ] || fail "Another release request is open: $prepare_open. Merge or close it first"

    prepare_start=$(git symbolic-ref --quiet --short HEAD || git rev-parse HEAD)
    RETURN_TO=$prepare_start

    step "Branch $prepare_branch"
    git checkout --quiet -B "$prepare_branch"

    step "Changelog"
    sh "$ROOT/scripts/changelog.sh" TAG="$prepare_tag"
    TEMP_FILE=$(mktemp)
    changelog_section "$prepare_version" <CHANGELOG.md >"$TEMP_FILE"
    [ -s "$TEMP_FILE" ] ||
        fail "Nothing for $prepare_tag in the changelog: no commit since $(tag_of "$prepare_current") changes the product"

    step "Version"
    printf '%s\n' "$prepare_version" >VERSION

    step "Commit and push"
    git add CHANGELOG.md VERSION
    git commit --quiet -m "chore(release): $prepare_tag"
    git push --quiet --force origin "$prepare_branch"

    step "Request"
    request_description "$prepare_tag" "$(tag_of "$prepare_current")" >"$TEMP_FILE"
    prepare_id=$(forge request id "$prepare_branch" 2>/dev/null || true)
    if [ -z "$prepare_id" ]; then
        forge request create --target "$RELEASE_BRANCH" --title "chore(release): $prepare_tag" \
            --body-file "$TEMP_FILE" --delete-branch
    else
        forge request url "$prepare_id"
    fi

    RETURN_TO=
    git checkout --quiet "$prepare_start"

    step "Done"
    echo "  Prepared: $prepare_tag; merging the request publishes it"
}

cd "$(git rev-parse --show-toplevel)"

step "Preflight"
[ -z "$(git status --porcelain)" ] || fail "Working tree is dirty — commit or stash first"
git fetch --quiet --tags --force origin "$RELEASE_BRANCH" || fail "Cannot reach origin"
git merge-base --is-ancestor HEAD "origin/$RELEASE_BRANCH" ||
    fail "Releases run from $RELEASE_BRANCH: HEAD is not on origin/$RELEASE_BRANCH"

current=$(version_at HEAD)
[ -n "$current" ] || fail "No VERSION file on HEAD"
current_tag=$(tag_of "$current")

# Publish only what a release commit set; any other origin of the version means "prepare".
setter=$(git log -1 --format=%H -G "^$(regex_literal "$current")\$" HEAD -- VERSION)
if [ -n "$setter" ] && is_release_commit "$setter" "$current_tag" &&
    { ! remote_tag_exists "$current_tag" || ! release_exists "$current_tag"; }; then
    [ -z "$VERSION" ] || fail "$current_tag is not published yet: run without VERSION to publish it, then prepare $VERSION"
    if remote_tag_exists "$current_tag"; then
        setter=$(git rev-parse "$current_tag^{commit}")
    fi
    publish "$current" "$setter"
else
    prepare "$current"
fi
